name: ML Pipeline CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Configure DVC remote auth
        run: |
          dvc remote modify dagshub auth basic
          dvc remote modify dagshub user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify dagshub password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull DVC data
        run: dvc pull

      - run: dvc repro -f